// Generated by https://quicktype.io

export interface RegisterResponse {
    jwt:  string;
    user: User;
}

export type LoginResponse = RegisterResponse;

export interface User {
    id:                  number;
    username:            string;
    email:               string;
    provider:            string;
    confirmed:           boolean;
    blocked:             boolean | null;
    role:                Role;
    created_at:          string;
    updated_at:          string;
    compositionsCreated: any[];
}

export interface Role {
    id:          number;
    name:        string;
    description: string;
    type:        string;
}
